# 按 Kanzi 官方 Application/bin 布局部署运行时文件。
# 工作目录根下需要 Studio EnginePlugins 目录中的系统 JAR（至少 kzjava.jar、kzjvm.jar）。

cmake_minimum_required(VERSION 3.15)

if(NOT CONFIG)
    message(FATAL_ERROR "deploy-runtime.cmake: CONFIG not set (Debug/Release)")
endif()
if(NOT KZB_DIRECTORY)
    message(FATAL_ERROR "deploy-runtime.cmake: KZB_DIRECTORY not set")
endif()

if(CONFIG MATCHES "Debug|RelWithDebInfo")
    set(_build_suffix "Debug")
    set(_fallback_suffix "Release")
else()
    set(_build_suffix "Release")
    set(_fallback_suffix "Debug")
endif()

macro(_append_studio_roots _list_var)
    if(DEFINED KANZI_STUDIO_HOME AND NOT "${KANZI_STUDIO_HOME}" STREQUAL "")
        list(APPEND ${_list_var} "${KANZI_STUDIO_HOME}")
    endif()
    if(DEFINED ENV{KANZI_STUDIO_HOME} AND NOT "$ENV{KANZI_STUDIO_HOME}" STREQUAL "")
        list(APPEND ${_list_var} "$ENV{KANZI_STUDIO_HOME}")
    endif()
    if(DEFINED KANZI_HOME AND NOT "${KANZI_HOME}" STREQUAL "")
        list(APPEND ${_list_var} "${KANZI_HOME}")
    endif()
    if(DEFINED ENV{KANZI_HOME} AND NOT "$ENV{KANZI_HOME}" STREQUAL "")
        list(APPEND ${_list_var} "$ENV{KANZI_HOME}")
    endif()
endmacro()

set(_studio_roots)
_append_studio_roots(_studio_roots)
list(REMOVE_DUPLICATES _studio_roots)

set(_engine_plugins_dir "")
foreach(_root IN LISTS _studio_roots)
    foreach(_bin IN ITEMS "Studio/Bin" "Bin")
        set(_candidate "${_root}/${_bin}/EnginePlugins")
        if(IS_DIRECTORY "${_candidate}")
            set(_engine_plugins_dir "${_candidate}")
            break()
        endif()
    endforeach()
    if(_engine_plugins_dir)
        break()
    endif()
endforeach()

# 先匹配 VS 配置（Debug/Release），再回退到另一套（本机可能只有 Release 目录）
set(_variant_dirs)
if(_engine_plugins_dir)
    foreach(_suffix IN ITEMS "${_build_suffix}" "${_fallback_suffix}")
        foreach(_vs IN ITEMS "vs2019" "vs2022")
            list(APPEND _variant_dirs "${_engine_plugins_dir}/GL_${_vs}_${_suffix}")
        endforeach()
    endforeach()
endif()

set(_selected_variant "")
foreach(_dir IN LISTS _variant_dirs)
    if(IS_DIRECTORY "${_dir}" AND (EXISTS "${_dir}/kzjava.jar" OR EXISTS "${_dir}/kzjvm.jar"))
        set(_selected_variant "${_dir}")
        break()
    endif()
endforeach()

if(_selected_variant)
    file(MAKE_DIRECTORY "${KZB_DIRECTORY}")
    file(GLOB _system_jars "${_selected_variant}/*.jar")
    foreach(_jar IN LISTS _system_jars)
        get_filename_component(_jar_name "${_jar}" NAME)
        execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different
            "${_jar}" "${KZB_DIRECTORY}/${_jar_name}")
        message(STATUS "deploy-runtime: ${_jar_name} <- ${_jar}")
    endforeach()
else()
    message(WARNING
        "deploy-runtime: no EnginePlugins variant with kzjava.jar/kzjvm.jar found.\n"
        "  searched: ${_variant_dirs}\n"
        "  set KANZI_STUDIO_HOME (e.g. D:/Kanzi 3_9_15_83) and rebuild.")
endif()

# --- 业务 Java 插件：仓库 plugins/ -> lib/java/<Debug|Release>/ ---
if(PLUGINS_DIRECTORY)
    set(_datasource "${PLUGINS_DIRECTORY}/datasource/lib/java/Release/DroidDataSourceplugin.jar")
    if(NOT EXISTS "${_datasource}")
        set(_datasource "${PLUGINS_DIRECTORY}/datasource/lib/java/Debug/DroidDataSourceplugin.jar")
    endif()
    if(EXISTS "${_datasource}")
        set(_dest_dir "${KZB_DIRECTORY}/lib/java/${_build_suffix}")
        file(MAKE_DIRECTORY "${_dest_dir}")
        execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different
            "${_datasource}" "${_dest_dir}/DroidDataSourceplugin.jar")
        message(STATUS "deploy-runtime: DroidDataSourceplugin.jar -> ${_dest_dir}/")
    else()
        message(WARNING "deploy-runtime: DroidDataSourceplugin.jar not found under ${PLUGINS_DIRECTORY}/datasource/")
    endif()
endif()
