from __future__ import annotations

import argparse
import logging
import sys
import time
from pathlib import Path

if __name__ == "__main__" and str(Path(__file__).resolve().parent) not in sys.path:
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from confluence_upload.client import ConfluenceClient
from confluence_upload.config import UploadConfig, page_title
from confluence_upload.document_renderer import RenderedDocument, SkippedDocument, render_document
from confluence_upload.paths import clean_export_work_dir
from confluence_upload.scanner import scan_documents

logger = logging.getLogger(__name__)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    logging.basicConfig(level=logging.INFO, format="%(message)s")

    project_root = Path(args.project_root).resolve()
    config = UploadConfig.load(
        project_root,
        docs_directory=Path(args.docs_dir).resolve() if args.docs_dir else None,
        export_directory=Path(args.export_dir).resolve() if args.export_dir else None,
        page_title_prefix=args.page_title_prefix,
        dry_run=args.dry_run,
    )

    config.export_directory.mkdir(parents=True, exist_ok=True)
    clean_export_work_dir(config.export_directory)

    documents = scan_documents(config)
    if not documents:
        logger.info("No documentation files found under %s", config.docs_directory)
        return 0

    client = ConfluenceClient(
        config.confluence_url,
        config.api_token,
        dry_run=config.dry_run,
        timeout_seconds=config.http_timeout_seconds,
    )

    logger.info("Uploading %s document(s) to Confluence", len(documents))
    space_key = client.get_space_key(config.parent_page_id)
    project_page_id = client.create_or_update_child_page(
        parent_id=config.parent_page_id,
        space_key=space_key,
        title=config.page_title_prefix,
        storage_html="<p>Project documentation root - auto-generated by Python script.</p>",
    )

    uploaded = 0
    skipped = 0
    failures: list[str] = []

    for index, document in enumerate(documents, start=1):
        logger.info("[%s/%s] %s", index, len(documents), document.name)
        try:
            outcome = render_document(config, document, project_root)
            if isinstance(outcome, SkippedDocument):
                logger.info("Skipped %s: %s", document.name, outcome.reason)
                skipped += 1
            else:
                _upload_rendered(client, project_page_id, space_key, config, document, outcome)
                uploaded += 1
        except Exception as error:
            failures.append(f"{document.name}: {error}")
            logger.error("Failed to upload %s: %s", document.name, error)

        if config.upload_delay_seconds > 0 and index < len(documents):
            time.sleep(config.upload_delay_seconds)

    logger.info(
        "Confluence upload finished: total=%s, uploaded=%s, skipped=%s, failed=%s",
        len(documents),
        uploaded,
        skipped,
        len(failures),
    )
    if failures:
        raise SystemExit("Confluence upload completed with failures:\n" + "\n".join(failures))
    return 0


def _upload_rendered(
    client: ConfluenceClient,
    project_page_id: str,
    space_key: str,
    config: UploadConfig,
    document: Path,
    rendered: RenderedDocument,
) -> None:
    title = page_title(config.page_title_prefix, document)
    page_id = client.create_or_update_child_page(
        parent_id=project_page_id,
        space_key=space_key,
        title=title,
        storage_html=rendered.storage_html,
    )
    for attachment in rendered.attachments:
        client.upload_attachment(page_id, attachment)
    logger.info("Uploaded: %s", title)


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Upload docs/architecture to Confluence.")
    parser.add_argument(
        "--project-root",
        default=".",
        help="Repository root (default: current directory)",
    )
    parser.add_argument(
        "--docs-dir",
        default=None,
        help="Docs directory to scan (default: docs/architecture)",
    )
    parser.add_argument(
        "--export-dir",
        default=None,
        help="Generated PNG export directory (default: docs/.confluence-export)",
    )
    parser.add_argument(
        "--page-title-prefix",
        default=None,
        help="Confluence page title prefix (default: project directory name)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Log actions without calling Confluence APIs",
    )
    return parser.parse_args(argv)


if __name__ == "__main__":
    sys.exit(main())
